---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  labels:
    app: odoo-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: odoo-db
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  labels:
    app: odoo-db
spec:
  selector:
    matchLabels:
      app: odoo-db
      tier: backend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo-db
        tier: backend
    spec:
      containers:
      - image: postgres:13
        name: odoo-db
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: test
        ports:
        - containerPort: 5432
          name: odoo-db
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  labels:
    app: odoo-shop
spec:
  ports:
  - port: 8069
    targetPort: 8069
  selector:
    app: odoo-shop
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  labels:
    app: odoo-shop
spec:
  selector:
    matchLabels:
      app: odoo-shop
      tier: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: frontend
    spec:
      containers:
      - image: odoo:14.0
        name: odoo-shop
        env:
        - name: POSTGRES_HOST
          value: odoo-db
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "odoo"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DATABASE
          value: "test"
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 8069
          name: odoo-shop